import type { Finding, Medication } from "@/lib/types";

const SEV_LABEL: Record<Finding["severity"], string> = {
  danger: "HIGH RISK",
  warning: "WORTH CHECKING",
  info: "FYI",
};

const MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

/** Locale-independent date so server and client render identically (no hydration mismatch). */
function formatDate(): string {
  const d = new Date();
  return `${MONTHS[d.getMonth()]} ${d.getDate()}, ${d.getFullYear()}`;
}

/** Shared summary markup — used both on screen (dialog) and in the print block. */
export function SummaryBody({
  meds,
  findings,
  sources,
}: {
  meds: Medication[];
  findings: Finding[];
  sources: string[];
}) {
  return (
    <div className="space-y-5 text-sm">
      <div>
        <h2 className="text-lg font-semibold tracking-tight">Medication summary</h2>
        <p className="text-muted-foreground">
          Prepared {formatDate()}
          {sources.length ? ` · Sources: ${sources.join(", ")}` : ""}
        </p>
      </div>

      <div>
        <h3 className="mb-2 font-semibold">Things to discuss ({findings.length})</h3>
        {findings.length === 0 ? (
          <p className="text-muted-foreground">No issues flagged.</p>
        ) : (
          <ul className="space-y-2">
            {findings.map((f) => (
              <li key={f.id} className="rounded-lg border p-3">
                <div className="font-medium">
                  [{SEV_LABEL[f.severity]}] {f.title}
                </div>
                <div className="mt-0.5 text-muted-foreground">{f.detail}</div>
                <div className="mt-1">
                  <span className="font-medium">Action:</span> {f.advice}
                </div>
              </li>
            ))}
          </ul>
        )}
      </div>

      <div>
        <h3 className="mb-2 font-semibold">
          Full medication list ({meds.length})
        </h3>
        <ul>
          {meds.map((m) => (
            <li
              key={m.id}
              className="flex flex-wrap justify-between gap-x-3 border-b py-1.5"
            >
              <span>
                {m.name}
                {m.occurrences > 1 ? ` (×${m.occurrences})` : ""}
              </span>
              <span className="text-muted-foreground">
                {m.prescriber} · {m.sourceLabel}
              </span>
            </li>
          ))}
        </ul>
      </div>

      <p className="text-xs text-muted-foreground">
        Generated by MedSafe from connected health records. Decision support
        only — not medical advice. Confirm everything with your doctor or
        pharmacist.
      </p>
    </div>
  );
}

/** Always in the DOM but hidden except when printing. */
export function PrintSummary(props: {
  meds: Medication[];
  findings: Finding[];
  sources: string[];
}) {
  return (
    <div className="print-only p-8">
      <SummaryBody {...props} />
    </div>
  );
}

/** Plain-text version for the "Copy" action. */
export function summaryToText(
  meds: Medication[],
  findings: Finding[],
  sources: string[],
): string {
  const lines: string[] = [];
  lines.push("MEDICATION SUMMARY");
  lines.push(`Prepared ${formatDate()}`);
  if (sources.length) lines.push(`Sources: ${sources.join(", ")}`);
  lines.push("");
  lines.push(`THINGS TO DISCUSS (${findings.length})`);
  if (findings.length === 0) lines.push("  None flagged.");
  for (const f of findings) {
    lines.push(`  [${SEV_LABEL[f.severity]}] ${f.title}`);
    lines.push(`    ${f.detail}`);
    lines.push(`    Action: ${f.advice}`);
  }
  lines.push("");
  lines.push(`FULL MEDICATION LIST (${meds.length})`);
  for (const m of meds) {
    const times = m.occurrences > 1 ? ` (x${m.occurrences})` : "";
    lines.push(`  - ${m.name}${times} — ${m.prescriber} · ${m.sourceLabel}`);
  }
  lines.push("");
  lines.push(
    "Generated by MedSafe. Decision support only — not medical advice.",
  );
  return lines.join("\n");
}
